name: batcat
base: core18
version: '0.18.2'
summary: A cat(1) clone with syntax highlighting and Git integration.
description: |
  This is a cat clone with more utilities and amazing features like syntax highlighting, Git integration
  and other cool stuffs.

grade: stable
confinement: strict

apps:
  batcat:
    command: bin/bat
    plugs:
      - home

parts:
  batcat:
    plugin: rust
    source: .
